version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: lappis
      POSTGRES_PASSWORD: lappis
      POSTGRES_DB: db_name
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres: