version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: lappis
      POSTGRES_PASSWORD: lappis
      POSTGRES_DB: db_name
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  metabase:
    image: metabase/metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
      MB_DB_DBNAME: db_name
      MB_DB_USER: lappis
      MB_DB_PASS: lappis
    volumes:
      - metabase:/metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  app:
    build: .
    volumes:
      - app:/app   

volumes:
  postgres:
  metabase:
  app:
