name: Publish package

on:
  release:
    types: [published]
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.8

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: deploy

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip3 install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install

      - name: Test
        run: |
          poetry run pytest

      - name: Set poetry version
        if: ${{ env.GITHUB_REF != '' }}
        run: |
          POETRY_VERSION=$(echo ${{ env.GITHUB_REF }} | awk -F'/' '{print $NF}')
          poetry version $POETRY_VERSION

      - name: Build
        run: |
          poetry build

      - name: Publish to PyPI
        if: ${{ env.GITHUB_REF != '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
