name: Publish package

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.8
  POETRY_VERSION: 1.0.10
  PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          poetry install

      - name: Test with poetry
        run: |
          poetry run pytest

      - name: Publish to PyPI with poetry
        if: env.PYPI_API_TOKEN
        env:
          PYPI_API_TOKEN: ${{ env.PYPI_API_TOKEN }}
        run: |
          poetry config pypi-token.pypi ${{ env.PYPI_API_TOKEN}}
          poetry publish
