name: Publish package

on:
  release:
    types: [published]
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.8
  POETRY_VERSION: 1.0.10

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: deploy

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip3 install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install

      - name: Test
        run: |
          poetry run pytest

      - name: Set Poetry version
        run: |
          poetry version $GITHUB_REF

      - name: Build
        run: |
          poetry build

      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
